@startuml
'https://plantuml.com/activity-diagram-beta

start
:Регистрируются все сущности, значения;
:Для сущностей и значений заполняются __details__;
if (Хуки) then (да)
:(БД) Создаются sqlalchemy-таблицы для сущностей. \nЗначения маппятся как части таблиц сущностей;
:;
else
endif
:Регистрируются все команды и запросы;
:Регистрируются все используемые ими интерфейсы компонентов;


stop

@enduml
