from enum import Enum

from ns.common.errors import Error


class ErrorCodes(Enum):
    DATA_CLASS_WAS_NOT_REGISTERED = 'DATA_CLASS_WAS_NOT_REGISTERED'
    LIST_MUST_HAVE_1_GENERIC_ARGUMENT = 'LIST_MUST_HAVE_1_GENERIC_ARGUMENT'
    LIST_MUST_HAVE_HAVE_ENTITY_ARGUMENT_IN_GENERIC = 'LIST_MUST_HAVE_HAVE_ENTITY_ARGUMENT_IN_GENERIC'
    TYPE_NOT_ALLOWED = 'TYPE_IS_NOT_ALLOWED'
    ENTITY_HAS_NO_ID = 'ENTITY_HAS_NO_ID'
    FIELD_IS_REQUIRED = 'FIELD_IS_REQUIRED'
    INVALID_FIELD_TYPE = 'INVALID_FIELD_TYPE'
    INVALID_RELATION_TYPE = 'INVALID_RELATION_TYPE'
    FIELD_CAN_NOT_HAVE_DEFAULT_VALUE = 'FIELD_CAN_NOT_HAVE_DEFAULT_VALUE'
    RELATION_WAS_NOT_CREATED = 'RELATION_WAS_NOT_CREATED'
    VALUE_HAS_NO_NATURAL_KEY = 'VALUE_HAS_NO_NATURAL_KEY'
    ID_NOT_FOUND = 'ID_NOT_FOUND'


class EntitiesError(Error[ErrorCodes]):
    """
    Ошибки обработки сущностей
    """
